name: Get Feed

on:
  schedule:
    - cron: '00 7 * * *' # UTC time mm hh
  workflow_dispatch:

jobs:
  get-feed:
    runs-on: ubuntu-latest
    env:
      NOTION_API_TOKEN: 'secret_LnaFfXq4xShp8FbP4q2bqFPmomkmLbGj4kcavnL2MsW'
      NOTION_READER_DATABASE_ID: '8773bd32d807470aad3fd02d5b6b37f6'
      NOTION_FEEDS_DATABASE_ID: '2b87503bf42243a4a0c717279d38de3e'
      RUN_FREQUENCY: 6000 # in seconds
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Update Notion Feed
        run: |
          curl -o index.js https://raw.githubusercontent.com/ravgeetdhillon/notion-feeder/build/dist/index.js
          node index.js
